"""
port_manager.py — 端口映射 + Nginx 配置生成/校验/回滚
"""
import os, shutil, subprocess, re
from pathlib import Path
from datetime import datetime
from typing import Optional


# Nginx 站点配置模板
NGINX_TEMPLATE = """# Auto-generated by Admin Console
# Generated: {generated_at}

server {{
    listen 80;
    server_name {server_name};
    client_max_body_size 10M;

    location {location_path} {{
        proxy_pass http://127.0.0.1:{backend_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }}
}}
"""


class PortConflictError(ValueError):
    """端口冲突"""
    pass


class PortManager:
    """端口映射可视化 + Nginx 配置生成/校验/reload/回滚"""

    def __init__(self, sites_dir: str, enabled_dir: str, app_base: str):
        self.app_base = Path(app_base)
        self.sites_dir = Path(sites_dir)
        self.enabled_dir = Path(enabled_dir)
        self.dry_run = bool(os.environ.get("DRY_RUN"))
        self._backup_dir = self.app_base / ".console_nginx_backups"

        if self.dry_run:
            # 使用临时目录
            self.sites_dir = Path("/tmp/console-dryrun/nginx/sites-available")
            self.enabled_dir = Path("/tmp/console-dryrun/nginx/sites-enabled")
            self._backup_dir = Path("/tmp/console-dryrun/nginx/backups")

        self.sites_dir.mkdir(parents=True, exist_ok=True)
        self.enabled_dir.mkdir(parents=True, exist_ok=True)
        self._backup_dir.mkdir(parents=True, exist_ok=True)

    # ── 服务端口映射 ──────────────────────────────────────────────

    # 默认映射
    DEFAULT_MAPPINGS = {
        "admin_console": {
            "service": "admin_console",
            "label": "管理控制台",
            "port": 9000,
            "server_name": "admin.gutbrainaxis.online",
            "location_path": "/",
        },
        "survey_feedback": {
            "service": "survey_feedback",
            "label": "问卷反馈页面",
            "port": 8000,
            "server_name": "api.gutbrainaxis.online",
            "location_path": "/",
        },
        "diet_feedback": {
            "service": "diet_feedback",
            "label": "饮食反馈页面",
            "port": 8001,
            "server_name": "svc.gutbrainaxis.online",
            "location_path": "/",
        },
        "webhook": {
            "service": "webhook",
            "label": "Webhook 接收器",
            "port": 9876,
            "server_name": "tools.gutbrainaxis.online",
            "location_path": "/",
        },
        "exercise_sync": {
            "service": "exercise_sync",
            "label": "运动问卷同步",
            "port": -1,
            "server_name": "",
            "location_path": "",
        },
    }

    def get_mappings(self) -> dict:
        """获取当前映射定义"""
        return dict(self.DEFAULT_MAPPINGS)

    # ── 冲突检测 ──────────────────────────────────────────────────

    def detect_conflicts(self, mappings: dict) -> list[str]:
        """
        检查端口重复、域名重复、端口被占用
        返回错误消息列表，空 = 无冲突
        """
        errors = []

        # 端口重复检测
        port_services = {}
        for name, m in mappings.items():
            p = m.get("port", -1)
            if p <= 0:
                continue
            if p in port_services:
                errors.append(f"端口 {p} 被多个服务占用: {port_services[p]}, {name}")
            port_services[p] = name

        # 域名重复检测
        domain_services = {}
        for name, m in mappings.items():
            d = m.get("server_name", "").strip()
            if not d:
                continue
            if d in domain_services:
                errors.append(f"域名 {d} 被多个服务映射: {domain_services[d]}, {name}")
            domain_services[d] = name

        # 端口被占用（非 dry-run）
        if not self.dry_run:
            for name, m in mappings.items():
                p = m.get("port", -1)
                if p <= 0:
                    continue
                if self._port_in_use(p):
                    errors.append(f"端口 {p} ({m.get('label', name)}) 已被系统中其他进程占用")

        return errors

    def _port_in_use(self, port: int) -> bool:
        """socket bind 探测端口是否已被占用"""
        import socket
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return False  # 绑定成功 → 空闲
            except OSError:
                return True  # 绑定失败 → 被占用

    # ── Nginx 配置生成 ────────────────────────────────────────────

    def generate_config(self, mappings: dict, preview: bool = True) -> dict:
        """
        生成 Nginx 站点配置。
        返回 {files: {site_name: content}, preview_lines: [diff], errors: [...]}
        不落盘，preview=True 时返回完整内容用于预览
        """
        result = {"files": {}, "preview_lines": [], "errors": []}

        # 按 server_name 分组（允许一个域名有多个 location）
        domain_services = {}
        for name, m in mappings.items():
            d = m.get("server_name", "").strip()
            if not d:
                continue
            p = m.get("port", -1)
            if p <= 0:
                continue
            domain_services.setdefault(d, []).append(m)

        for domain, services in domain_services.items():
            locations = ""
            for svc in services:
                loc = svc.get("location_path", "/")
                port = svc.get("port", 80)
                locations += f"""
    location {loc} {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }}
"""

            config = f"""# Auto-generated by Admin Console
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

server {{
    listen 80;
    server_name {domain};
    client_max_body_size 10M;
    {locations}
}}
"""
            result["files"][domain] = config

        # 生成预览行
        if preview:
            lines = []
            for fname, content in result["files"].items():
                lines.append(f"=== {fname} ===")
                lines.extend(content.splitlines())
            # 同时显示"当前 vs 新"的对比
            for fname, content in result["files"].items():
                current = "（当前无此配置 / 无法读取）"
                current_path = self.sites_dir / fname
                if current_path.exists():
                    try:
                        current = current_path.read_text()
                    except OSError:
                        pass
                lines.append("")
                lines.append(f"--- 当前 / --- 新 {fname}")
                current_lines = current.splitlines()
                new_lines = content.splitlines()
                max_lines = max(len(current_lines), len(new_lines))
                for i in range(max_lines):
                    c = current_lines[i] if i < len(current_lines) else ""
                    n_ = new_lines[i] if i < len(new_lines) else ""
                    marker = " " if c == n_ else "*"
                    lines.append(f"{marker} -{c}")
                    lines.append(f"{marker} +{n_}")
            result["preview_lines"] = lines

        return result

    # ── 写盘 + 校验 + reload + 回滚 ──────────────────────────────

    def apply_and_reload(self, mappings: dict) -> dict:
        """
        完整流程：备份 → 写配置 → nginx -t → reload → 成功/回滚
        返回 {success, errors, rollback, message}
        """
        result = {"success": True, "errors": [], "rollback": False, "message": ""}

        # 1. 冲突检测
        conflicts = self.detect_conflicts(mappings)
        if conflicts:
            result["success"] = False
            result["errors"] = conflicts
            result["message"] = "冲突检测未通过"
            return result

        # 2. 生成配置
        gen = self.generate_config(mappings, preview=False)
        if gen.get("errors"):
            result["success"] = False
            result["errors"] = gen["errors"]
            result["message"] = "配置生成失败"
            return result

        # 3. Dry-run 模式：模拟成功
        if self.dry_run:
            for fname, content in gen["files"].items():
                (self.sites_dir / fname).write_text(content)
            result["message"] = "[DRY_RUN] 模拟成功"
            return result

        # 4. 备份当前配置
        backup_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_dst = self._backup_dir / backup_id
        backup_dst.mkdir(parents=True, exist_ok=True)
        for f in self.sites_dir.glob("*"):
            if f.is_file():
                shutil.copy2(str(f), str(backup_dst / f.name))

        # 5. 写新配置
        try:
            for fname, content in gen["files"].items():
                (self.sites_dir / fname).write_text(content)
        except OSError as e:
            result["success"] = False
            result["errors"].append(f"写配置失败: {e}")
            self._rollback(backup_dst)
            result["rollback"] = True
            result["message"] = "写配置失败，已回滚"
            return result

        # 6. 创建符号链接到 sites-enabled
        for fname in gen["files"]:
            src = self.sites_dir / fname
            dst = self.enabled_dir / fname
            try:
                if not dst.exists():
                    dst.symlink_to(os.path.relpath(str(src), str(self.enabled_dir)))
            except OSError as e:
                result["errors"].append(f"sites-enabled 链接创建失败: {e}")

        # 7. nginx -t 校验
        try:
            r = subprocess.run(
                ["nginx", "-t"],
                capture_output=True, text=True, timeout=10
            )
            if r.returncode != 0:
                error_msg = r.stderr or r.stdout or "配置校验失败"
                self._rollback(backup_dst)
                result["success"] = False
                result["rollback"] = True
                result["errors"].append(f"nginx -t 失败: {error_msg[:300]}")
                result["message"] = "Nginx 配置校验失败，已回滚"
                return result
        except FileNotFoundError:
            # nginx 命令不存在，降级为仅写配置
            result["message"] = "配置已写入（未发现 nginx 命令，跳过校验和 reload）"
            return result
        except subprocess.TimeoutExpired:
            result["errors"].append("nginx -t 超时")
            self._rollback(backup_dst)
            result["success"] = False
            result["rollback"] = True
            result["message"] = "nginx -t 超时，已回滚"
            return result

        # 8. systemctl reload nginx
        try:
            r = subprocess.run(
                ["systemctl", "reload", "nginx"],
                capture_output=True, text=True, timeout=15
            )
            if r.returncode != 0:
                # reload 失败不回滚（配置已通过校验）
                result["errors"].append(f"systemctl reload nginx 失败: {r.stderr[:200]}")
                result["message"] = "配置已写入且通过校验，但 reload 失败（需手动 reload）"
                return result
        except FileNotFoundError:
            result["message"] = "配置已写入并通过校验（未发现 systemctl）"
            return result

        result["message"] = "配置已写入、通过校验、nginx 已 reload"
        return result

    # ── 回滚 ──────────────────────────────────────────────────────

    def _rollback(self, backup_dir: Path):
        """从备份目录恢复配置"""
        if not backup_dir.exists():
            return
        for f in backup_dir.glob("*"):
            if f.is_file():
                dst = self.sites_dir / f.name
                shutil.copy2(str(f), str(dst))
